package p152o1;

/* renamed from: o1.k */
/* loaded from: classes.dex */
public abstract class AbstractC1905k {

    /* renamed from: a */
    public static final C1896b f7864a;

    /* renamed from: b */
    public static final C1896b f7865b;

    /* renamed from: c */
    public static final C1896b f7866c;

    /* renamed from: d */
    public static final C1896b f7867d;

    static {
        new C1896b(0, "VISUAL_STATE_CALLBACK", "VISUAL_STATE_CALLBACK");
        new C1896b(0, "OFF_SCREEN_PRERASTER", "OFF_SCREEN_PRERASTER");
        new C1896b(3, "SAFE_BROWSING_ENABLE", "SAFE_BROWSING_ENABLE");
        new C1896b(1, "DISABLED_ACTION_MODE_MENU_ITEMS", "DISABLED_ACTION_MODE_MENU_ITEMS");
        new C1896b(4, "START_SAFE_BROWSING", "START_SAFE_BROWSING");
        new C1896b(4, "SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_WHITELIST");
        new C1896b(4, "SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_ALLOWLIST");
        new C1896b(4, "SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_WHITELIST");
        new C1896b(4, "SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_ALLOWLIST");
        new C1896b(4, "SAFE_BROWSING_PRIVACY_POLICY_URL", "SAFE_BROWSING_PRIVACY_POLICY_URL");
        new C1896b(1, "SERVICE_WORKER_BASIC_USAGE", "SERVICE_WORKER_BASIC_USAGE");
        new C1896b(1, "SERVICE_WORKER_CACHE_MODE", "SERVICE_WORKER_CACHE_MODE");
        new C1896b(1, "SERVICE_WORKER_CONTENT_ACCESS", "SERVICE_WORKER_CONTENT_ACCESS");
        new C1896b(1, "SERVICE_WORKER_FILE_ACCESS", "SERVICE_WORKER_FILE_ACCESS");
        new C1896b(1, "SERVICE_WORKER_BLOCK_NETWORK_LOADS", "SERVICE_WORKER_BLOCK_NETWORK_LOADS");
        new C1896b(1, "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST");
        new C1896b(0, "RECEIVE_WEB_RESOURCE_ERROR", "RECEIVE_WEB_RESOURCE_ERROR");
        new C1896b(0, "RECEIVE_HTTP_ERROR", "RECEIVE_HTTP_ERROR");
        new C1896b(1, "SHOULD_OVERRIDE_WITH_REDIRECTS", "SHOULD_OVERRIDE_WITH_REDIRECTS");
        new C1896b(4, "SAFE_BROWSING_HIT", "SAFE_BROWSING_HIT");
        new C1896b(1, "WEB_RESOURCE_REQUEST_IS_REDIRECT", "WEB_RESOURCE_REQUEST_IS_REDIRECT");
        f7864a = new C1896b(0, "WEB_RESOURCE_ERROR_GET_DESCRIPTION", "WEB_RESOURCE_ERROR_GET_DESCRIPTION");
        f7865b = new C1896b(0, "WEB_RESOURCE_ERROR_GET_CODE", "WEB_RESOURCE_ERROR_GET_CODE");
        new C1896b(4, "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY");
        new C1896b(4, "SAFE_BROWSING_RESPONSE_PROCEED", "SAFE_BROWSING_RESPONSE_PROCEED");
        new C1896b(4, "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL");
        new C1896b(0, "WEB_MESSAGE_PORT_POST_MESSAGE", "WEB_MESSAGE_PORT_POST_MESSAGE");
        new C1896b(0, "WEB_MESSAGE_PORT_CLOSE", "WEB_MESSAGE_PORT_CLOSE");
        new C1896b(2, "WEB_MESSAGE_ARRAY_BUFFER", "WEB_MESSAGE_ARRAY_BUFFER");
        new C1896b(0, "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK");
        new C1896b(0, "CREATE_WEB_MESSAGE_CHANNEL", "CREATE_WEB_MESSAGE_CHANNEL");
        new C1896b(0, "POST_WEB_MESSAGE", "POST_WEB_MESSAGE");
        new C1896b(0, "WEB_MESSAGE_CALLBACK_ON_MESSAGE", "WEB_MESSAGE_CALLBACK_ON_MESSAGE");
        new C1896b(3, "GET_WEB_VIEW_CLIENT", "GET_WEB_VIEW_CLIENT");
        new C1896b(3, "GET_WEB_CHROME_CLIENT", "GET_WEB_CHROME_CLIENT");
        new C1896b(6, "GET_WEB_VIEW_RENDERER", "GET_WEB_VIEW_RENDERER");
        new C1896b(6, "WEB_VIEW_RENDERER_TERMINATE", "WEB_VIEW_RENDERER_TERMINATE");
        new C1896b(5, "TRACING_CONTROLLER_BASIC_USAGE", "TRACING_CONTROLLER_BASIC_USAGE");
        new C1900f();
        new C1900f();
        new C1900f();
        new C1896b(6, "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE");
        new C1903i();
        new C1896b(2, "PROXY_OVERRIDE", "PROXY_OVERRIDE:3");
        f7866c = new C1896b(2, "MULTI_PROCESS", "MULTI_PROCESS_QUERY");
        new C1896b(6, "FORCE_DARK", "FORCE_DARK");
        new C1896b(2, "FORCE_DARK_STRATEGY", "FORCE_DARK_BEHAVIOR");
        new C1896b(2, "WEB_MESSAGE_LISTENER", "WEB_MESSAGE_LISTENER");
        new C1896b(2, "DOCUMENT_START_SCRIPT", "DOCUMENT_START_SCRIPT:1");
        new C1896b(2, "PROXY_OVERRIDE_REVERSE_BYPASS", "PROXY_OVERRIDE_REVERSE_BYPASS");
        new C1896b(2, "GET_VARIATIONS_HEADER", "GET_VARIATIONS_HEADER");
        new C1896b(2, "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY");
        new C1896b(2, "GET_COOKIE_INFO", "GET_COOKIE_INFO");
        new C1896b(2, "REQUESTED_WITH_HEADER_ALLOW_LIST", "REQUESTED_WITH_HEADER_ALLOW_LIST");
        new C1896b(2, "USER_AGENT_METADATA", "USER_AGENT_METADATA");
        new C1904j(0, "MULTI_PROFILE", "MULTI_PROFILE");
        new C1896b(2, "ATTRIBUTION_REGISTRATION_BEHAVIOR", "ATTRIBUTION_BEHAVIOR");
        new C1896b(2, "WEBVIEW_MEDIA_INTEGRITY_API_STATUS", "WEBVIEW_INTEGRITY_API_STATUS");
        new C1896b(2, "MUTE_AUDIO", "MUTE_AUDIO");
        new C1896b(2, "WEB_AUTHENTICATION", "WEB_AUTHENTICATION");
        new C1896b(2, "SPECULATIVE_LOADING_STATUS", "SPECULATIVE_LOADING");
        new C1896b(2, "BACK_FORWARD_CACHE", "BACK_FORWARD_CACHE");
        new C1896b(2, "DELETE_BROWSING_DATA", "WEB_STORAGE_DELETE_BROWSING_DATA");
        new C1904j(1, "PREFETCH_URL_V4", "PREFETCH_URL_V4");
        new C1896b(2, "IMPLEMENTATION_ONLY_FEATURE", "ASYNC_WEBVIEW_STARTUP");
        new C1896b(2, "DEFAULT_TRAFFICSTATS_TAGGING", "DEFAULT_TRAFFICSTATS_TAGGING");
        new C1896b(2, "PRERENDER_URL_V2", "PRERENDER_URL_V2");
        new C1896b(2, "SPECULATIVE_LOADING_CONFIG_V2", "SPECULATIVE_LOADING_CONFIG_V2");
        new C1896b(2, "SAVE_STATE", "SAVE_STATE");
        new C1896b(2, "WEB_VIEW_NAVIGATION_CLIENT_BASIC_USAGE", "WEB_VIEW_NAVIGATION_CLIENT_BASIC_USAGE");
        new C1896b(2, "CACHE_PROVIDER", "PROVIDER_WEAKLY_REF_WEBVIEW");
        f7867d = new C1896b(2, "PAYMENT_REQUEST", "PAYMENT_REQUEST");
        new C1896b(2, "WEBVIEW_BUILDER", "WEBVIEW_BUILDER");
    }
}
